### ISSUE TITLE
Fata Error: IPC Table

### ISSUE THREAD

**Issue by gwythan** [arcanebyte/lisaem#1]
I have successfully compiled LisaEm on an M1 Mac running OS 14.1 :-)

Starting up from any drive (ProFile or Floppy) gives the following error:

Sorry, the emulation aborted due to a fatal error
Couldn't get IPC Table! Doh!
Stopped at cpu68k.c:cpu68k_makeipclist:1056 with code :21
LisaEM will now quit.

Is this a bug? Incompatibility? User error??
Kind regards, Kevin.

**Comment by busterswt** [comment]
Hi Kevin,

The issue you're experiencing is related to a bug with "romless" mode. The workaround is to use a legitimate Lisa ROM file.

Howto:

1. Source and download the Lisa ROM files named 3410175H.bin and 3410176H.bin
2. Rename 3410175H.bin to boot.hi and 3410176H.bin to boot.lo
3. Launch the LisaEM app. When it opens, go to Preferences. Within "Lisa ROM", browse to boot.hi. Then hit Apply. This will generate a boot.ROM file within the same directory.
4. Quit LisaEm
5. Reopen LisaEm

At this point, try booting from Floppy or Profile again. If the issue persists, let me know.,
