### ISSUE TITLE
Hello! LisaEm Crashes when booting with LOS

### ISSUE THREAD

**Issue by MatiLol251** [arcanebyte/lisaem#2]
As i said before on other repo of LisaEm:
"This happened to me in RC4 and RC3. However, in the sable release this doesn't happen. What's going on?
![image](https://github.com/rayarachelian/lisaem/assets/106706551/7e1d0791-4848-47f3-ac31-78c8e38f952e)
maybe is the fact that is a _release candidate_."

**Comment by busterswt** [comment]
The issue you're experiencing is likely related to a bug with "romless" mode. The workaround is to use a legitimate Lisa ROM file.

Howto:

1. Source and download the Lisa ROM files named 3410175H.bin and 3410176H.bin
2. Rename 3410175H.bin to boot.hi and 3410176H.bin to boot.lo
3. Launch the LisaEM app. When it opens, go to Preferences. Within "Lisa ROM", browse to boot.hi. Then hit Apply. This will generate a boot.ROM file within the same directory.
4. Quit LisaEm
5. Reopen LisaEm

At this point, try booting from Floppy or Profile again. If the issue persists, let me know.

**Comment by MatiLol251** [comment]
I can install LOS now. Thank you!
